### ISSUE TITLE
Recreating after destroy() bug when type "double" having "from" and "to" options

### ISSUE THREAD

**Issue by prettycode** [IonDen/ion.rangeSlider#230] opened 2015-04-23 18:16 UTC
I took the destroy example from: http://ionden.com/a/plugins/ion.rangeSlider/demo_advanced.html

And put it in a jsFiddle: http://jsfiddle.net/krn3p9rj/

And it works.

However, when I introduce `from` and `to` options, it does not work after `destroy()`. To reproduce, see this: http://jsfiddle.net/krn3p9rj/1/

When the jsFiddle above loads, follow these steps:

1. Click "Create range slider"
2. Click "Destroy"
3. Click "Create range slider"

Expected: range slider shows 0 - 500.
Actual: range slider shows 0 - 1000.

**Comment by IonDen** [comment] 2015-04-23 19:10
Hi, seems to be a bug.

**Comment by prettycode** [comment] 2015-04-23 22:06
As a workaround I'm clearing the value of the input after I `destroy()`. It appears that the value of the input takes precedent over the slider options passed in when you're creating the slider after it's been destroyed. Maybe this value-takes-precedent-over-slider-options is by design?

**Comment by IonDen** [comment] 2015-05-30 09:51
Hi, no it is a bug. By design JS config should have a priority.

**Comment by IonDen** [comment] 2015-05-30 10:39
Fixed in 2.0.8

**Closed by IonDen** 2015-05-30 10:39 UTC
Labels: Minor bug
