### ISSUE TITLE
Slider position resets to minimum on single slider for certain combination of from value and step

### ISSUE THREAD

**Issue by megals** [IonDen/ion.rangeSlider#245] opened 2015-05-29 15:22 UTC
Hi,
I'm having issue detailed below with the slider.

Slider position resets to minimum on a slider type single for certain values. This happens specifically when we call the slider update after initialising the slider with the values mentioned.

Example values:
Slider max and from as 4.75 and step value 0.10
Slider max and from as 2.28 and step value 0.20

The slider works fine for the values given below
Slider max and from as 4.71 and step value 0.10
Slider max and from as 2.24 and step value 0.20

If you would like to see the slider behaviour for all these examples, please check http://jsfiddle.net/Megala/d8gf0k2t/

Your response to this will be much appreciated.

Thanks

**Comment by IonDen** [comment] 2015-05-30 08:58
Hello, i see.
I will investigate the problem.

**Comment by IonDen** [comment] 2015-05-30 10:40
Tnx for mention the problem. Fixed in 2.0.8

**Closed by IonDen** 2015-05-30 10:40 UTC
Labels: Bug

**Comment by megals** [comment] 2015-05-30 11:10
Thank you very much for a quick turn around. Much appreciated.

I will test it and will confirm the same.

**Comment by IonDen** [comment] 2015-05-30 11:11
I already tested on your demo. Just use Ctrl+R

**Comment by megals** [comment] 2015-05-30 15:41
Many thanks. But there is one other issue I see there for case 3, which I didn't mention earlier.
The issue is when the max value is say 4.71 and step value is 0.01, then the slider position is set to 4.7 and not 4.71. Again it looks like a rounding issue.

Could you please check this too?

Thanks in advance.

**Comment by IonDen** [comment] 2015-05-30 20:33
Please check again. It should not round x.71 to x.7 if step is 0.01. If the problem is still there, please set up another ticket with demos.

**Comment by megals** [comment] 2015-05-30 20:53
Sorry, it was my typo. The step value is not 0.01. The problem occurs only if the step value is 0.10
Please let me know if you still want me to raise it as a separate bug?

Also, case 3 in my current demo has this problem. Please check this link http://jsfiddle.net/Megala/d8gf0k2t/

Many thanks again for your response.

**Comment by IonDen** [comment] 2015-05-30 20:55
I can't really say what it is a bug. If the value is x.71 and step is 0.1 it should be rounded to x.7? Isn't it?

**Comment by megals** [comment] 2015-05-30 21:18
The issue is I don't want the slider value to round down, because it is the money value. In this case x.70 is 1 pence lesser than the x.71.

Let say slider maximum is x.74, even in this case it rounds the maximum to x.70 and doesn't let the slider pointer to move forwards to get the value of x.74.

But if you give slider maximum as x.75 or above, then it works perfectly. It allows the slider pointer to move up to x.75

You can clearly see that slider pointer label saying 4.75 for case 1 (as expected). and 4.7 for case 3. But expected result for case 3 is 4.71

In all the above cases, the step value is 0.10

Hope I have explained it clearly. If not, please let me know.

Thanks.

**Comment by IonDen** [comment] 2015-05-30 21:19
Ok i understand. Please set up another issue for that.

**Comment by megals** [comment] 2015-05-30 21:23
Thanks. Will do it now.
