### ISSUE TITLE
max_postfix setting intermittently applied 

### ISSUE THREAD

**Issue by Wolfe13** [IonDen/ion.rangeSlider#219] opened 2015-03-27 23:43 UTC
When I set max_postfix to a value I am noticing that under certain circumstances and in certain places it is not displayed alongside the maximum value. For instance, I am using the following code to generate this slider:
```
$('input#capacity-range').ionRangeSlider({
    from: 0,
    to: 500,
    min: 0,
    max: 500,
    type: 'double', 
    grid: true, 
    force_edges: true, 
    keyword: true, 
    min_interval: 5, 
    keyboard_step: 5,
    step: 5,
    max_postfix: "+"
  });
```
![screen shot 2015-03-27 at 7 29 06 pm](https://cloud.githubusercontent.com/assets/8104895/6878621/a2b4368c-d4b7-11e4-9983-0b2d0653b94b.png)
As you can understand, it is important for my users to see the + after the 500. It is visible on the top of the pictures above and below although I would ultimately like to remove the set of labels shown in grey. I am unable to do that though because the timeline on the bottom is all that I'd be left with and that is missing the max_postfix on the 500. 

![screen shot 2015-03-27 at 7 28 31 pm](https://cloud.githubusercontent.com/assets/8104895/6878623/a4dfeef6-d4b7-11e4-98d3-9a18bfe86a5d.png)

![screen shot 2015-03-27 at 7 28 13 pm](https://cloud.githubusercontent.com/assets/8104895/6878624/a847a96c-d4b7-11e4-935d-422e997f9b7d.png)
Even if I manage to do the above however, I run into another problem. This (ingenious -- thanks!) feature you thought up to combine the labels when the max / min range sliders are too close seems to have a bug in it. If the sliders combine and include the max label, the max_postfix suffix ceases to be applied as you can see above. 

If you could make the max_postfix setting consistently visible I would be most appreciative!

**Comment by IonDen** [comment] 2015-03-30 12:52
Hi, ok.

**Comment by IonDen** [comment] 2015-05-30 10:39
Fixed in 2.0.8

**Closed by IonDen** 2015-05-30 10:39 UTC
Labels: Minor bug

**Comment by mvastola** [comment] 2015-06-01 05:10
Thanks for this fix. With the latest version of this plugin, I can get the following, which is much better:
![ionRangeSlider](https://cloud.githubusercontent.com/assets/599767/7906468/c6fd666a-07f9-11e5-817e-d08cd36efc9b.png)

Question though.. is it by design that the 500 in light gray on the bottom right is lacking the postfix '+' or is that still a remnant of this bug? When you accepted this, I just assumed the postfix would be made to be shown there as well, but I can understand if you made a conscious decision to the contrary. (I myself am still debating which way I would like it to be...)

**Comment by IonDen** [comment] 2015-06-01 08:23
Hi, i am not really sure if it is ok to have + there) I will think about it.

**Comment by mvastola** [comment] 2015-06-01 08:50
Ok. I'm still trying to decide if I want it shown there too. I just thought it made sense to clear up this question now though for the sake of completeness.
